### ISSUE TITLE
Cropping Camera Images Are Rotated

### ISSUE THREAD

**Issue by tonespy** [fahidattique55/FAImageCropper#6]
Images taken with the use of the iPhone camera app are rotated clockwise or anti-clockwise. I first experienced it last year and fixed it. Liked your implementation here and decided to commit to the repo and make a PR, but couldn't. So, I want to ask do you accept PRs?

**Comment by fahidattique55** [comment]
Hi tonespy,

Yes, you are always welcome for PRs.

Thanks & Regards

**Comment by tonespy** [comment]
```
ERROR: Permission to fahidattique55/FAImageCropper.git denied to tonespy.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
The repo does not allow write access

**Comment by fahidattique55** [comment]
Hi tonespy,

I have verified the access level of this repo. Its working fine for all other users. Can you please verify once again at your side.

Please let me know if it works, meanwhile I am trying to diagnose the issue you are facing.

Thanks & Regards

**Comment by tonespy** [comment]
Same thing. I created a feature branch to work, but the remote repo wouldn't accept the push.

**Comment by fahidattique55** [comment]
Hi @tonespy,

I just forked and create a new PR. It is working fine at my end. Please verify the following steps so that I can verify that we are on the same page of discussion.

1. Login to your GitHub account
2. Fork the repository i.e FAImageCropper
3. Clone the forked repository with Https or SSH git url to your working machine
4. Integrate the updated code you want to contribute in FAImageCropper
5. Commit and push to your forked repository
6. Login/Open GitHub -> Go to forked repository
7. Create a Pull request from GitHub

Feel free to ask If you face any further issue.

Thanks & Regards
